runtime: nodejs20
env: standard
instance_class: F2 # (옵션) 필요한 리소스에 따라 인스턴스 클래스 조정 가능

env_variables:
  SUPABASE_URL: 'https://kbenmmgflqjdksimhzbx.supabase.co'
  SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZW5tbWdmbHFqZGtzaW1oemJ4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczMjg2Nzk3MCwiZXhwIjoyMDQ4NDQzOTcwfQ.zwuZkXHLBb55TDskuohoq8CU6U5Oa0Z9QKx_GumusTY'
  PINATA_API_KEY: '1bf266f1fe120987d6d6'
  PINATA_API_SECRET: 'd964c55fb8553c251851e2bc676b891160a82cb44e50b2870fda28e0dcfed81a'
  PINATA_JWT: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiIzZDFiYThiNS01YTc5LTQxOTktYTQwNS1kY2YyZjhjNjM2NTgiLCJlbWFpbCI6ImpqYzg5NzVAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInBpbl9wb2xpY3kiOnsicmVnaW9ucyI6W3siZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiRlJBMSJ9LHsiZGVzaXJlZFJlcGxpY2F0aW9uQ291bnQiOjEsImlkIjoiTllDMSJ9XSwidmVyc2lvbiI6MX0sIm1mYV9lbmFibGVkIjpmYWxzZSwic3RhdHVzIjoiQUNUSVZFIn0sImF1dGhlbnRpY2F0aW9uVHlwZSI6InNjb3BlZEtleSIsInNjb3BlZEtleUtleSI6IjFiZjI2NmYxZmUxMjA5ODdkNmQ2Iiwic2NvcGVkS2V5U2VjcmV0IjoiZDk2NGM1NWZiODU1M2MyNTE4NTFlMmJjNjc2Yjg5MTE2MGE4MmNiNDRlNTBiMjg3MGZkYTI4ZTBkY2ZlZDgxYSIsImV4cCI6MTc3MTc0NzI1MH0.U9Bb3z9k6xTVo1lSv3KVvTHqrcgpQpmUzLZhMn3Xlr4'
  JWT_SECRET_KEY: 'wepublic&bluenode+pocproject'
  NODE_ENV: 'development'
